sudo: false
language: ruby
before_script: .travis/before.sh
install: bundle install --deployment --without development production
rvm: 2.1.3
cache: bundler
branches:
  only:
  - master
addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-server-dev-9.4
